### ISSUE TITLE
Unable to get the token

### ISSUE THREAD

**Issue by syam38** [twilio/video-quickstart-js#12]
The chrome console gives me the following error:

`Error: accountSid is required
    at new AccessToken (D:\video-quickstart-js\node_modules\twilio\lib\jwt\AccessToken.js:184:28)
    at D:\video-quickstart-js\server\index.js:44:15
    at Layer.handle [as handle_request] (D:\video-quickstart-js\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\video-quickstart-js\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\video-quickstart-js\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\video-quickstart-js\node_modules\express\lib\router\layer.js:95:5)
    at D:\video-quickstart-js\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\video-quickstart-js\node_modules\express\lib\router\index.js:335:12)
    at next (D:\video-quickstart-js\node_modules\express\lib\router\index.js:275:10)
    at expressInit (D:\video-quickstart-js\node_modules\express\lib\middleware\init.js:40:5)`

This is my .env file
TWILIO_ACCOUNT_SID=[my-account-sid]
TWILIO_API_KEY=[my-api-key]
TWILIO_API_SECRET=[my-api-secret-key]

**Comment by kommanasai** [comment]
Iam getting above error. How can i resolve this error please suggests

**Comment by engsomya** [comment]
Same error. Please advise asap!!
