### ISSUE TITLE
Permission denied when running `npm start`

### ISSUE THREAD

**Issue by brayann** [twilio/video-quickstart-js#222]
Hello, just cloned the project and after I ran `npm install` and then tried to boot the app with `npm start` I got the following error:

```
> video-quickstart-js@1.0.0-dev build:examples:bandwidthconstraints
> copyfiles -f examples/bandwidthconstraints/src/helpers.js examples/bandwidthconstraints/public && browserify examples/bandwidthconstraints/src/index.js > examples/bandwidthconstraints/public/index.js

node:internal/fs/utils:347
    throw err;
    ^

Error: EACCES: permission denied, write
    at writeSync (node:fs:934:3)
    at SyncWriteStream._write (node:internal/fs/sync_write_stream:26:3)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Readable.ondata (/home/brayan/www/pvt/video-quickstart-js/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at Readable.emit (node:events:513:28)
    at addChunk (/home/brayan/www/pvt/video-quickstart-js/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/home/brayan/www/pvt/video-quickstart-js/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Readable.push (/home/brayan/www/pvt/video-quickstart-js/node_modules/readable-stream/lib/_stream_readable.js:245:10) {
  errno: -13,
  syscall: 'write',
  code: 'EACCES'
}

Node.js v18.16.0
ERROR: "build:examples:bandwidthconstraints" exited with 1.
ERROR: "build:examples" exited with 1.
```
Tried running as root, deleting node_modules and installing again but same error, could this be due to my system/node version or something?

**Comment by brayann** [comment]
Well, ignore me :) tried with yarn and worked fine!
