### ISSUE TITLE
TwilioError: Participant identity is invalid

### ISSUE THREAD

**Issue by rasheedsaidi** [twilio/video-quickstart-js#33]
The following function is used to generate an accessToken for the rooms connection.
public function joinRoom($roomName)
	{
		// A unique identifier for this user
		$identity = Auth::user()->name;
		\Log::debug("joined with identity: $identity");
		$token = new AccessToken($this->sid, $this->key, $this->secret, 3600, $identity);

		$videoGrant = new VideoGrant();
		$videoGrant->setRoom($roomName);

		$token->addGrant($videoGrant);

		return view('room.room', [ 'accessToken' => $token->toJWT(), 'roomName' => $roomName ]);
	}

The accessToken was passed to the frontend where it is consumed by the following javascript:
var room_data = @json(['accessToken' => $accessToken, 'roomName' => $roomName]);
        Twilio.Video.createLocalTracks({
           audio: true,
           video: { width: 300 }
        }).then(function(localTracks) { console.log(room_data['accessToken'], room_data['roomName'])
           return Twilio.Video.connect(room_data['accessToken'], {
               name: room_data['roomName'],
               tracks: localTracks,
               video: { width: 300 }
           });
        }).then(function(room) {
           console.log('Successfully joined a Room: ', room.name);

           room.participants.forEach(participantConnected);

           var previewContainer = document.getElementById(room.localParticipant.sid);
           if (!previewContainer || !previewContainer.querySelector('video')) {
               participantConnected(room.localParticipant);
           }

           room.on('participantConnected', function(participant) {
               console.log("Joining: '" + participant.identity + "'");
               participantConnected(participant);
           });

           room.on('participantDisconnected', function(participant) {
               console.log("Disconnected: '" + participant.identity + "'");
               participantDisconnected(participant);
           });
        }).catch( function(err) {
            console.log(err);
        });

Unfortunately, I got the following error:
TwilioError: Participant identity is invalid↵    at ParticipantIdentityInvalidError.TwilioError (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:94:27053)↵    at new ParticipantIdentityInvalidError (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:94:21063)↵    at createTwilioError (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:94:13281)↵    at getTwilioErrorFromRequestOrResponseBody (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:93:4338)↵    at getTwilioErrorFromRequestOrResponse (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:93:4909)↵    at InviteClientContext.disconnect (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:93:5167)↵    at InviteClientContext.g (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:103:25946)↵    at InviteClientContext.EventEmitter.emit (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:103:24433)↵    at InviteClientContext.failed (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:98:18113)↵    at InviteClientContext.receiveInviteResponse (https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/twilio-video.min.js:99:11849)

Any idea what I'm doing wrong?

**Comment by manjeshbhargav** [comment]
Hi @rasheedsaidi ,

Can you post the identity string that you are using to create the AccessToken? You can get the `ParticipantIdentityInvalidError` for the following reasons:
* The identity is `null` or an empty string.
* Another Participant with the same identity already exists in the Room.
* The identity has more than 128 characters (NOTE: Double-byte characters are counted as 2 characters).

Hopefully, this should help you work around your issue. Please let me know if you this helps.

Thanks,

Manjesh Malavalli

**Comment by nxkhiem1991** [comment]
> @manjeshbhargav Thank you for your response. I was able to get past the ParticipantIdentityInvalidError using your suggestions above.
> 
> Thank you.

I am also having the same error. How did you fix it? @saidiadegoke
